from __future__ import annotations

import copy
import hashlib
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw, ImageFont
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from sqlalchemy import func, select
from sqlalchemy.orm import Session, joinedload

from app.core.config import get_settings
from app.db.models import (
    Advisee,
    AdvisingMeeting,
    Assignment,
    AttendanceRecord,
    Course,
    Enrollment,
    GradeEntry,
    InteractionLog,
    ReportTemplate,
    ReportTemplateAsset,
    RubricEvaluation,
    RubricTemplate,
    StoredDocument,
    StoredDocumentStudentLink,
    StoredDocumentVersion,
    StudentProfile,
    Task,
)


BRAND_TITLE = "Jon's Gradebook"

SECTION_DEFAULTS: list[dict[str, Any]] = [
    {"key": "student_profile", "label": "Student Snapshot", "enabled": True, "order": 10, "options": {"show_email": True, "show_courses": True}},
    {"key": "grade_overview", "label": "Grade Overview", "enabled": True, "order": 20, "options": {"limit": 8, "show_scores": True}},
    {"key": "attendance", "label": "Attendance", "enabled": True, "order": 30, "options": {"show_empty": True}},
    {"key": "rubric_evaluations", "label": "Rubric Evaluations", "enabled": True, "order": 40, "options": {"limit": 6, "item_limit": 6, "show_notes": True, "show_scores": True}},
    {"key": "recent_interactions", "label": "Recent Interactions", "enabled": True, "order": 50, "options": {"limit": 10}},
    {"key": "advising_meetings", "label": "Advising Meetings", "enabled": False, "order": 60, "options": {"limit": 5, "show_action_items": True}},
    {"key": "tasks", "label": "Tasks and Interventions", "enabled": False, "order": 70, "options": {"limit": 8, "show_done": False}},
    {"key": "linked_documents", "label": "Linked Documents", "enabled": False, "order": 80, "options": {"limit": 8}},
]

BASE_TEMPLATE_CONFIG: dict[str, Any] = {
    "metadata": {
        "report_title": "Student Report",
        "footer_text": "Generated by Jon's Gradebook",
    },
    "theme": {
        "primary_color": "#1b2840",
        "accent_color": "#d9a441",
        "neutral_color": "#f5f7fb",
        "font_scale": 1.0,
        "header_style": "band",
        "logo_asset_id": None,
    },
    "sections": SECTION_DEFAULTS,
}


def _wrap_text(text: str, max_chars: int) -> list[str]:
    words = (text or "").split()
    lines: list[str] = []
    current = ""
    for word in words:
        next_line = f"{current} {word}".strip()
        if len(next_line) > max_chars and current:
            lines.append(current)
            current = word
        else:
            current = next_line
    if current:
        lines.append(current)
    return lines or [""]


def _score_label(total_points: float | None, max_points: float | None) -> str:
    if total_points is not None and max_points is not None:
        return f"{total_points}/{max_points}"
    if total_points is not None:
        return str(total_points)
    return "N/A"


def _merge_config(base: dict[str, Any], override: dict[str, Any] | None) -> dict[str, Any]:
    merged = copy.deepcopy(base)
    if not override:
        return merged

    for key, value in override.items():
        if key == "sections" and isinstance(value, list):
            by_key = {section["key"]: copy.deepcopy(section) for section in merged.get("sections", []) if section.get("key")}
            for raw_section in value:
                if not isinstance(raw_section, dict) or not raw_section.get("key"):
                    continue
                section_key = raw_section["key"]
                current = by_key.get(section_key, {"key": section_key, "label": section_key.replace("_", " ").title(), "enabled": True, "order": 999, "options": {}})
                current.update({k: v for k, v in raw_section.items() if k != "options"})
                current["options"] = {**current.get("options", {}), **raw_section.get("options", {})}
                by_key[section_key] = current
            merged["sections"] = sorted(by_key.values(), key=lambda section: (section.get("order", 999), section.get("label", "")))
        elif isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _merge_config(merged[key], value)
        else:
            merged[key] = value
    return merged


def normalize_report_config(config: dict[str, Any] | None) -> dict[str, Any]:
    normalized = _merge_config(BASE_TEMPLATE_CONFIG, config or {})
    normalized["sections"] = sorted(
        normalized.get("sections", []),
        key=lambda section: (int(section.get("order", 999)), str(section.get("label", ""))),
    )
    return normalized


def default_report_template_payloads() -> list[dict[str, Any]]:
    def with_sections(title: str, enabled: set[str], overrides: dict[str, dict[str, Any]] | None = None) -> dict[str, Any]:
        config = copy.deepcopy(BASE_TEMPLATE_CONFIG)
        config["metadata"]["report_title"] = title
        config["sections"] = []
        for section in SECTION_DEFAULTS:
            next_section = copy.deepcopy(section)
            next_section["enabled"] = next_section["key"] in enabled
            if overrides and next_section["key"] in overrides:
                next_section = _merge_config(next_section, overrides[next_section["key"]])
            config["sections"].append(next_section)
        return config

    return [
        {
            "name": "Progress Snapshot",
            "description": "Balanced student progress report with grades, attendance, rubric feedback, and recent contact.",
            "is_default": True,
            "config_json": with_sections(
                "Progress Snapshot",
                {"student_profile", "grade_overview", "attendance", "rubric_evaluations", "recent_interactions"},
            ),
        },
        {
            "name": "Rubric Feedback Report",
            "description": "Detailed rubric-centered report for assignment feedback and student conferences.",
            "is_default": False,
            "config_json": with_sections(
                "Rubric Feedback Report",
                {"student_profile", "rubric_evaluations", "recent_interactions"},
                {"rubric_evaluations": {"order": 20, "options": {"limit": 10, "item_limit": 10, "show_notes": True}}},
            ),
        },
        {
            "name": "Advising Summary",
            "description": "Advising-oriented report with meetings, tasks, interactions, and linked records.",
            "is_default": False,
            "config_json": with_sections(
                "Advising Summary",
                {"student_profile", "advising_meetings", "tasks", "recent_interactions", "linked_documents"},
            ),
        },
        {
            "name": "Intervention Follow-Up",
            "description": "Focused intervention report for risk review and recovery planning.",
            "is_default": False,
            "config_json": with_sections(
                "Intervention Follow-Up",
                {"student_profile", "grade_overview", "attendance", "tasks", "recent_interactions"},
                {"tasks": {"order": 35, "options": {"limit": 10, "show_done": True}}},
            ),
        },
    ]


def ensure_default_report_templates(db: Session) -> None:
    existing_count = db.scalar(select(func.count(ReportTemplate.id)))
    if existing_count:
        return

    for payload in default_report_template_payloads():
        db.add(
            ReportTemplate(
                name=payload["name"],
                description=payload["description"],
                report_type="student",
                is_active=True,
                is_default=payload["is_default"],
                config_json=normalize_report_config(payload["config_json"]),
            )
        )
    db.commit()


def _latest_logo_asset(template: ReportTemplate | None) -> ReportTemplateAsset | None:
    if not template:
        return None
    logo_id = normalize_report_config(template.config_json).get("theme", {}).get("logo_asset_id")
    logos = [asset for asset in template.assets if asset.asset_type == "logo"]
    if logo_id:
        for asset in logos:
            if asset.id == logo_id:
                return asset
    return sorted(logos, key=lambda asset: asset.created_at or datetime.min.replace(tzinfo=timezone.utc), reverse=True)[0] if logos else None


def serialize_report_template(template: ReportTemplate) -> dict[str, Any]:
    logo = _latest_logo_asset(template)
    settings = get_settings()
    return {
        "id": template.id,
        "name": template.name,
        "description": template.description,
        "report_type": template.report_type,
        "is_active": template.is_active,
        "is_default": template.is_default,
        "archived_at": template.archived_at.isoformat() if template.archived_at else None,
        "config_json": normalize_report_config(template.config_json),
        "created_at": template.created_at.isoformat() if template.created_at else None,
        "updated_at": template.updated_at.isoformat() if template.updated_at else None,
        "logo_asset": {
            "id": logo.id,
            "original_filename": logo.original_filename,
            "mime_type": logo.mime_type,
            "size_bytes": logo.size_bytes,
            "url": f"{settings.api_v1_prefix}/reports/templates/{template.id}/assets/logo",
        }
        if logo
        else None,
    }


def set_default_template(db: Session, template: ReportTemplate) -> None:
    templates = db.scalars(select(ReportTemplate).where(ReportTemplate.report_type == template.report_type)).all()
    for row in templates:
        row.is_default = row.id == template.id


def save_template_logo(db: Session, template: ReportTemplate, filename: str, content: bytes, mime_type: str) -> ReportTemplateAsset:
    if not content:
        raise ValueError("Uploaded logo is empty")
    if not (mime_type.startswith("image/") or Path(filename).suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".webp"}):
        raise ValueError("Logo must be an image")

    digest = hashlib.sha256(content).hexdigest()[:16]
    suffix = Path(filename).suffix.lower() or ".bin"
    settings = get_settings()
    asset_dir = Path(settings.storage_root) / "reports" / "assets" / str(template.id)
    asset_dir.mkdir(parents=True, exist_ok=True)
    asset_path = asset_dir / f"logo-{digest}{suffix}"
    asset_path.write_bytes(content)

    asset = ReportTemplateAsset(
        template_id=template.id,
        asset_type="logo",
        original_filename=filename,
        mime_type=mime_type,
        file_path=str(asset_path),
        size_bytes=len(content),
    )
    db.add(asset)
    db.flush()
    config = normalize_report_config(template.config_json)
    config.setdefault("theme", {})["logo_asset_id"] = asset.id
    template.config_json = config
    db.commit()
    db.refresh(asset)
    db.refresh(template)
    return asset


def _student_summary(
    db: Session,
    student_id: int,
    include_all_rubrics: bool = True,
    rubric_id: int | None = None,
    assignment_id: int | None = None,
) -> dict[str, Any]:
    student = db.scalar(
        select(StudentProfile)
        .where(StudentProfile.id == student_id)
        .options(joinedload(StudentProfile.enrollments).joinedload(Enrollment.course))
    )
    if not student:
        raise ValueError("Student not found")

    attendance_rows = db.scalars(select(AttendanceRecord).where(AttendanceRecord.student_id == student_id)).all()
    attendance_counts = Counter(record.status.value for record in attendance_rows)

    interaction_rows = db.scalars(
        select(InteractionLog).where(InteractionLog.student_profile_id == student_id).order_by(InteractionLog.occurred_at.desc())
    ).all()

    grade_rows = db.execute(
        select(GradeEntry, Assignment)
        .join(Assignment, GradeEntry.assignment_id == Assignment.id)
        .where(GradeEntry.student_id == student_id)
    ).all()
    grade_overview_by_course: dict[int, dict[str, Any]] = defaultdict(
        lambda: {
            "course_name": "Unknown Course",
            "earned": 0.0,
            "possible": 0.0,
            "graded_items": 0,
        }
    )
    for grade, assignment in grade_rows:
        bucket = grade_overview_by_course[assignment.course_id]
        bucket["course_name"] = next(
            (enrollment.course.name for enrollment in student.enrollments if enrollment.course_id == assignment.course_id),
            f"Course {assignment.course_id}",
        )
        if assignment.points_possible is not None:
            bucket["possible"] += float(assignment.points_possible)
        if grade.score is not None:
            bucket["earned"] += float(grade.score)
            bucket["graded_items"] += 1

    grade_overview = []
    for course_id, bucket in grade_overview_by_course.items():
        possible = float(bucket["possible"])
        earned = float(bucket["earned"])
        grade_overview.append(
            {
                "course_id": course_id,
                "course_name": bucket["course_name"],
                "earned": round(earned, 2),
                "possible": round(possible, 2),
                "percent": round((earned / possible) * 100.0, 2) if possible > 0 else None,
                "graded_items": int(bucket["graded_items"]),
            }
        )
    grade_overview.sort(key=lambda row: row["course_name"])

    rubric_query = (
        select(RubricEvaluation)
        .where(RubricEvaluation.student_profile_id == student_id)
        .order_by(RubricEvaluation.created_at.desc())
    )
    if not include_all_rubrics:
        if rubric_id is not None:
            rubric_query = rubric_query.where(RubricEvaluation.rubric_id == rubric_id)
        if assignment_id is not None:
            rubric_query = rubric_query.where(RubricEvaluation.assignment_id == assignment_id)
    rubric_evals = db.scalars(rubric_query.limit(50)).all()

    rubric_ids = {evaluation.rubric_id for evaluation in rubric_evals}
    rubric_map = {
        rubric.id: rubric
        for rubric in (db.scalars(select(RubricTemplate).where(RubricTemplate.id.in_(rubric_ids))).all() if rubric_ids else [])
    }
    criterion_map = {
        criterion.id: criterion
        for rubric in rubric_map.values()
        for criterion in rubric.criteria
    }
    rating_map = {
        rating.id: rating
        for criterion in criterion_map.values()
        for rating in criterion.ratings
    }
    course_ids = {evaluation.course_id for evaluation in rubric_evals if evaluation.course_id is not None}
    assignment_ids = {evaluation.assignment_id for evaluation in rubric_evals if evaluation.assignment_id is not None}
    course_map = {
        course.id: course
        for course in (db.scalars(select(Course).where(Course.id.in_(course_ids))).all() if course_ids else [])
    }
    assignment_map = {
        assignment.id: assignment
        for assignment in (
            db.scalars(select(Assignment).where(Assignment.id.in_(assignment_ids))).all() if assignment_ids else []
        )
    }

    advisee = db.scalar(select(Advisee).where(Advisee.student_profile_id == student_id))
    advising_rows = (
        db.scalars(
            select(AdvisingMeeting)
            .where(AdvisingMeeting.advisee_id == advisee.id)
            .order_by(AdvisingMeeting.meeting_at.desc())
            .limit(20)
        ).all()
        if advisee
        else []
    )

    task_rows = db.scalars(
        select(Task).where(Task.linked_student_id == student_id).order_by(Task.created_at.desc()).limit(50)
    ).all()

    document_links = db.scalars(
        select(StoredDocumentStudentLink).where(StoredDocumentStudentLink.student_id == student_id)
    ).all()
    document_ids = {link.document_id for link in document_links}
    documents = (
        db.scalars(select(StoredDocument).where(StoredDocument.id.in_(document_ids)).order_by(StoredDocument.updated_at.desc())).all()
        if document_ids
        else []
    )
    versions = (
        db.scalars(select(StoredDocumentVersion).where(StoredDocumentVersion.document_id.in_(document_ids))).all()
        if document_ids
        else []
    )
    latest_version_by_doc: dict[int, StoredDocumentVersion] = {}
    for version in versions:
        current = latest_version_by_doc.get(version.document_id)
        if current is None or version.version_number > current.version_number:
            latest_version_by_doc[version.document_id] = version

    return {
        "student": student,
        "courses": [enrollment.course.name for enrollment in student.enrollments],
        "grade_overview": grade_overview,
        "attendance": dict(attendance_counts),
        "rubric_scope": {
            "include_all_rubrics": include_all_rubrics,
            "rubric_id": rubric_id,
            "assignment_id": assignment_id,
        },
        "rubric_evaluations": [
            {
                "id": evaluation.id,
                "rubric_name": rubric_map.get(evaluation.rubric_id).name if rubric_map.get(evaluation.rubric_id) else None,
                "total_points": evaluation.total_points,
                "max_points": rubric_map.get(evaluation.rubric_id).max_points if rubric_map.get(evaluation.rubric_id) else None,
                "course_name": course_map.get(evaluation.course_id).name if evaluation.course_id and course_map.get(evaluation.course_id) else None,
                "assignment_title": assignment_map.get(evaluation.assignment_id).title if evaluation.assignment_id and assignment_map.get(evaluation.assignment_id) else None,
                "created_at": evaluation.created_at.isoformat(),
                "evaluator_notes": evaluation.evaluator_notes,
                "items": [
                    {
                        "id": item.id,
                        "criterion_id": item.criterion_id,
                        "criterion_title": criterion_map.get(item.criterion_id).title if criterion_map.get(item.criterion_id) else "Criterion",
                        "criterion_type": criterion_map.get(item.criterion_id).criterion_type.value if criterion_map.get(item.criterion_id) else None,
                        "criterion_max_points": criterion_map.get(item.criterion_id).max_points if criterion_map.get(item.criterion_id) else None,
                        "rating_id": item.rating_id,
                        "rating_title": rating_map.get(item.rating_id).title if item.rating_id and rating_map.get(item.rating_id) else None,
                        "rating_description": rating_map.get(item.rating_id).description if item.rating_id and rating_map.get(item.rating_id) else None,
                        "points_awarded": item.points_awarded,
                        "is_checked": item.is_checked,
                        "narrative_comment": item.narrative_comment,
                        "display_order": criterion_map.get(item.criterion_id).display_order if criterion_map.get(item.criterion_id) else 0,
                    }
                    for item in sorted(
                        evaluation.items,
                        key=lambda row: (criterion_map.get(row.criterion_id).display_order if criterion_map.get(row.criterion_id) else 0, row.id),
                    )
                ],
            }
            for evaluation in rubric_evals
        ],
        "recent_interactions": [
            {
                "type": interaction.interaction_type.value,
                "summary": interaction.summary,
                "occurred_at": interaction.occurred_at.isoformat(),
            }
            for interaction in interaction_rows[:20]
        ],
        "advising_meetings": [
            {
                "id": meeting.id,
                "meeting_at": meeting.meeting_at.isoformat(),
                "mode": meeting.mode.value,
                "summary": meeting.summary,
                "action_items": meeting.action_items,
            }
            for meeting in advising_rows
        ],
        "tasks": [
            {
                "id": task.id,
                "title": task.title,
                "status": task.status.value,
                "priority": task.priority.value,
                "due_at": task.due_at.isoformat() if task.due_at else None,
                "note": task.note,
                "source": task.source,
            }
            for task in task_rows
        ],
        "linked_documents": [
            {
                "id": document.id,
                "title": document.title,
                "category": document.category,
                "document_type": document.document_type.value,
                "updated_at": document.updated_at.isoformat() if document.updated_at else None,
                "latest_filename": latest_version_by_doc.get(document.id).original_filename if latest_version_by_doc.get(document.id) else None,
            }
            for document in documents
        ],
    }


def _enabled_sections(config: dict[str, Any]) -> list[dict[str, Any]]:
    return [section for section in config.get("sections", []) if section.get("enabled", True)]


def _section_limit(section: dict[str, Any], default: int) -> int:
    try:
        return max(1, min(int(section.get("options", {}).get("limit", default)), 50))
    except (TypeError, ValueError):
        return default


def _theme_color(config: dict[str, Any], key: str, fallback: str) -> str:
    value = str(config.get("theme", {}).get(key) or fallback).strip()
    if len(value) == 7 and value.startswith("#"):
        return value
    return fallback


def _font_scale(config: dict[str, Any]) -> float:
    try:
        return max(0.85, min(float(config.get("theme", {}).get("font_scale", 1.0)), 1.25))
    except (TypeError, ValueError):
        return 1.0


def _pdf_text(pdf: canvas.Canvas, x: float, y: float, text: str, font: str, size: float, color: str = "#14213d") -> None:
    pdf.setFillColor(HexColor(color))
    pdf.setFont(font, size)
    pdf.drawString(x, y, text)


def _pdf_ensure_space(pdf: canvas.Canvas, y: float, min_height: float, page_height: float, footer_text: str) -> float:
    if y - min_height >= 58:
        return y
    _pdf_footer(pdf, footer_text)
    pdf.showPage()
    return page_height - 60


def _pdf_footer(pdf: canvas.Canvas, footer_text: str) -> None:
    pdf.setFillColor(HexColor("#64748b"))
    pdf.setFont("Helvetica", 8)
    pdf.drawString(50, 32, footer_text[:100])
    pdf.drawRightString(562, 32, datetime.now(timezone.utc).strftime("%Y-%m-%d"))


def _draw_pdf(report_path: Path, summary: dict[str, Any], config: dict[str, Any], logo: ReportTemplateAsset | None) -> None:
    pdf = canvas.Canvas(str(report_path), pagesize=LETTER)
    _, height = LETTER
    primary = _theme_color(config, "primary_color", "#1b2840")
    accent = _theme_color(config, "accent_color", "#d9a441")
    neutral = _theme_color(config, "neutral_color", "#f5f7fb")
    scale = _font_scale(config)
    metadata = config.get("metadata", {})
    title = str(metadata.get("report_title") or "Student Report")
    footer_text = str(metadata.get("footer_text") or "Generated by Jon's Gradebook")
    student = summary["student"]

    y = height - 58
    if config.get("theme", {}).get("header_style") == "band":
        pdf.setFillColor(HexColor(primary))
        pdf.rect(0, height - 116, 612, 116, stroke=0, fill=1)
        title_color = "#ffffff"
        sub_color = "#f8fafc"
    else:
        title_color = primary
        sub_color = "#334155"

    if logo and Path(logo.file_path).exists():
        try:
            pdf.drawImage(ImageReader(logo.file_path), 50, height - 96, width=52, height=52, preserveAspectRatio=True, mask="auto")
            title_x = 116
        except Exception:
            title_x = 50
    else:
        title_x = 50

    _pdf_text(pdf, title_x, y, title[:54], "Helvetica-Bold", 18 * scale, title_color)
    y -= 22
    _pdf_text(pdf, title_x, y, f"{student.first_name} {student.last_name}".strip() or "Student", "Helvetica", 11 * scale, sub_color)
    if student.student_number:
        pdf.drawRightString(562, y, f"Student #{student.student_number}")
    y = height - 148

    for section in _enabled_sections(config):
        y = _pdf_ensure_space(pdf, y, 70, height, footer_text)
        label = str(section.get("label") or section.get("key") or "Section")
        pdf.setFillColor(HexColor(neutral))
        pdf.roundRect(50, y - 22, 512, 26, 5, stroke=0, fill=1)
        pdf.setFillColor(HexColor(accent))
        pdf.rect(50, y - 22, 5, 26, stroke=0, fill=1)
        _pdf_text(pdf, 64, y - 13, label[:80], "Helvetica-Bold", 11.5 * scale, primary)
        y -= 40
        key = section.get("key")
        options = section.get("options", {})

        if key == "student_profile":
            rows = [
                f"Email: {student.email or 'N/A'}",
                "Courses: " + (", ".join(summary["courses"]) or "None"),
            ]
            for row in rows:
                _pdf_text(pdf, 62, y, row[:112], "Helvetica", 9.5 * scale)
                y -= 15
        elif key == "grade_overview":
            rows = summary["grade_overview"][: _section_limit(section, 8)]
            if rows:
                for row in rows:
                    y = _pdf_ensure_space(pdf, y, 22, height, footer_text)
                    percent = f"{row['percent']}%" if row["percent"] is not None else "N/A"
                    score = f"{row['earned']}/{row['possible']} ({percent})" if options.get("show_scores", True) else percent
                    _pdf_text(pdf, 62, y, f"{row['course_name']}: {score}"[:112], "Helvetica", 9.5 * scale)
                    y -= 15
            else:
                _pdf_text(pdf, 62, y, "No grade data available", "Helvetica", 9.5 * scale)
                y -= 15
        elif key == "attendance":
            line = "   ".join(f"{status.title()}: {summary['attendance'].get(status, 0)}" for status in ("present", "absent", "tardy", "excused"))
            _pdf_text(pdf, 62, y, line, "Helvetica", 9.5 * scale)
            y -= 18
        elif key == "rubric_evaluations":
            evaluations = summary["rubric_evaluations"][: _section_limit(section, 6)]
            item_limit = int(options.get("item_limit", 6) or 6)
            if evaluations:
                for evaluation in evaluations:
                    y = _pdf_ensure_space(pdf, y, 76, height, footer_text)
                    score = _score_label(evaluation["total_points"], evaluation["max_points"]) if options.get("show_scores", True) else ""
                    target = evaluation["assignment_title"] or evaluation["course_name"] or "General"
                    _pdf_text(pdf, 62, y, (evaluation["rubric_name"] or "Rubric")[:62], "Helvetica-Bold", 9.5 * scale, primary)
                    pdf.drawRightString(552, y, f"{score}  {evaluation['created_at'][:10]}".strip())
                    y -= 13
                    _pdf_text(pdf, 62, y, target[:98], "Helvetica", 8.5 * scale, "#475569")
                    y -= 18
                    for item in evaluation.get("items", [])[:item_limit]:
                        y = _pdf_ensure_space(pdf, y, 34, height, footer_text)
                        rating = item.get("rating_title") or ("Checked" if item.get("is_checked") else "No rating")
                        points = _score_label(item.get("points_awarded"), item.get("criterion_max_points")) if options.get("show_scores", True) else ""
                        _pdf_text(pdf, 72, y, f"{item['criterion_title']}: {rating}"[:88], "Helvetica", 8.5 * scale)
                        if points:
                            pdf.drawRightString(552, y, points)
                        y -= 12
                        detail = item.get("rating_description") or item.get("narrative_comment") or ""
                        if detail:
                            _pdf_text(pdf, 82, y, detail[:96], "Helvetica", 7.8 * scale, "#64748b")
                            y -= 12
                    if options.get("show_notes", True) and evaluation.get("evaluator_notes"):
                        for line in _wrap_text(f"Notes: {evaluation['evaluator_notes']}", 96)[:2]:
                            _pdf_text(pdf, 72, y, line, "Helvetica-Oblique", 8.2 * scale, "#475569")
                            y -= 12
                    y -= 8
            else:
                _pdf_text(pdf, 62, y, "No rubric evaluations available", "Helvetica", 9.5 * scale)
                y -= 15
        elif key == "recent_interactions":
            rows = summary["recent_interactions"][: _section_limit(section, 10)]
            if rows:
                for interaction in rows:
                    y = _pdf_ensure_space(pdf, y, 18, height, footer_text)
                    line = f"{interaction['occurred_at'][:10]} [{interaction['type']}] {interaction['summary']}"
                    _pdf_text(pdf, 62, y, line[:112], "Helvetica", 8.5 * scale)
                    y -= 13
            else:
                _pdf_text(pdf, 62, y, "No recent interactions", "Helvetica", 9.5 * scale)
                y -= 15
        elif key == "advising_meetings":
            rows = summary["advising_meetings"][: _section_limit(section, 5)]
            for meeting in rows:
                y = _pdf_ensure_space(pdf, y, 28, height, footer_text)
                _pdf_text(pdf, 62, y, f"{meeting['meeting_at'][:10]} ({meeting['mode'].replace('_', ' ')}) {meeting.get('summary') or ''}"[:112], "Helvetica", 8.5 * scale)
                y -= 13
                if options.get("show_action_items", True) and meeting.get("action_items"):
                    _pdf_text(pdf, 72, y, f"Actions: {meeting['action_items']}"[:104], "Helvetica", 8 * scale, "#64748b")
                    y -= 12
            if not rows:
                _pdf_text(pdf, 62, y, "No advising meetings linked to this student", "Helvetica", 9.5 * scale)
                y -= 15
        elif key == "tasks":
            tasks = [task for task in summary["tasks"] if options.get("show_done", False) or task["status"] != "done"][: _section_limit(section, 8)]
            for task in tasks:
                y = _pdf_ensure_space(pdf, y, 18, height, footer_text)
                due = f" due {task['due_at'][:10]}" if task.get("due_at") else ""
                _pdf_text(pdf, 62, y, f"[{task['priority']}/{task['status']}] {task['title']}{due}"[:112], "Helvetica", 8.5 * scale)
                y -= 13
            if not tasks:
                _pdf_text(pdf, 62, y, "No matching tasks", "Helvetica", 9.5 * scale)
                y -= 15
        elif key == "linked_documents":
            documents = summary["linked_documents"][: _section_limit(section, 8)]
            for document in documents:
                y = _pdf_ensure_space(pdf, y, 18, height, footer_text)
                _pdf_text(pdf, 62, y, f"{document['title']} ({document['category']} / {document['document_type']})"[:112], "Helvetica", 8.5 * scale)
                y -= 13
            if not documents:
                _pdf_text(pdf, 62, y, "No linked documents", "Helvetica", 9.5 * scale)
                y -= 15
        y -= 14

    _pdf_footer(pdf, footer_text)
    pdf.save()


def _pil_color(value: str, fallback: str) -> str:
    return value if len(value) == 7 and value.startswith("#") else fallback


def _png_text(draw: ImageDraw.ImageDraw, x: int, y: int, text: str, color: str, font: ImageFont.ImageFont) -> None:
    draw.text((x, y), text, fill=color, font=font)


def _draw_png(image_path: Path, summary: dict[str, Any], config: dict[str, Any], logo: ReportTemplateAsset | None) -> None:
    primary = _pil_color(_theme_color(config, "primary_color", "#1b2840"), "#1b2840")
    accent = _pil_color(_theme_color(config, "accent_color", "#d9a441"), "#d9a441")
    neutral = _pil_color(_theme_color(config, "neutral_color", "#f5f7fb"), "#f5f7fb")
    image = Image.new("RGB", (1200, 1600), neutral)
    draw = ImageDraw.Draw(image)
    font_title = ImageFont.load_default()
    font_body = ImageFont.load_default()
    metadata = config.get("metadata", {})
    title = str(metadata.get("report_title") or "Student Report")
    student = summary["student"]

    if config.get("theme", {}).get("header_style") == "band":
        draw.rectangle((0, 0, 1200, 170), fill=primary)
        title_color = "#ffffff"
        sub_color = "#f8fafc"
    else:
        title_color = primary
        sub_color = "#334155"

    title_x = 52
    if logo and Path(logo.file_path).exists():
        try:
            logo_image = Image.open(logo.file_path).convert("RGBA")
            logo_image.thumbnail((96, 96))
            image.paste(logo_image, (52, 38), logo_image)
            title_x = 170
        except Exception:
            title_x = 52

    _png_text(draw, title_x, 48, title[:90], title_color, font_title)
    _png_text(draw, title_x, 84, f"{student.first_name} {student.last_name}".strip(), sub_color, font_body)
    if student.student_number:
        _png_text(draw, title_x, 110, f"Student #{student.student_number}", sub_color, font_body)

    y = 205
    for section in _enabled_sections(config):
        if y > 1490:
            break
        label = str(section.get("label") or section.get("key") or "Section")
        draw.rounded_rectangle((42, y, 1158, y + 42), radius=8, fill="#ffffff", outline="#d7dee8")
        draw.rectangle((42, y, 52, y + 42), fill=accent)
        _png_text(draw, 70, y + 14, label[:90], primary, font_title)
        y += 62
        key = section.get("key")
        options = section.get("options", {})

        lines: list[str] = []
        if key == "student_profile":
            lines = [f"Email: {student.email or 'N/A'}", "Courses: " + (", ".join(summary["courses"]) or "None")]
        elif key == "grade_overview":
            for row in summary["grade_overview"][: _section_limit(section, 8)]:
                percent = f"{row['percent']}%" if row["percent"] is not None else "N/A"
                score = f"{row['earned']}/{row['possible']} ({percent})" if options.get("show_scores", True) else percent
                lines.append(f"{row['course_name']}: {score}")
            if not lines:
                lines.append("No grade data available")
        elif key == "attendance":
            lines.append("   ".join(f"{status.title()}: {summary['attendance'].get(status, 0)}" for status in ("present", "absent", "tardy", "excused")))
        elif key == "rubric_evaluations":
            for evaluation in summary["rubric_evaluations"][: _section_limit(section, 6)]:
                score = _score_label(evaluation["total_points"], evaluation["max_points"]) if options.get("show_scores", True) else ""
                lines.append(f"{evaluation['created_at'][:10]} {evaluation['rubric_name'] or 'Rubric'} {score}".strip())
                for item in evaluation.get("items", [])[: int(options.get("item_limit", 4) or 4)]:
                    rating = item.get("rating_title") or ("Checked" if item.get("is_checked") else "No rating")
                    lines.append(f"  {item['criterion_title']}: {rating}")
            if not lines:
                lines.append("No rubric evaluations available")
        elif key == "recent_interactions":
            for interaction in summary["recent_interactions"][: _section_limit(section, 10)]:
                lines.append(f"{interaction['occurred_at'][:10]} [{interaction['type']}] {interaction['summary']}")
            if not lines:
                lines.append("No recent interactions")
        elif key == "advising_meetings":
            for meeting in summary["advising_meetings"][: _section_limit(section, 5)]:
                lines.append(f"{meeting['meeting_at'][:10]} {meeting['mode'].replace('_', ' ')}: {meeting.get('summary') or ''}")
            if not lines:
                lines.append("No advising meetings linked to this student")
        elif key == "tasks":
            for task in [task for task in summary["tasks"] if options.get("show_done", False) or task["status"] != "done"][: _section_limit(section, 8)]:
                lines.append(f"[{task['priority']}/{task['status']}] {task['title']}")
            if not lines:
                lines.append("No matching tasks")
        elif key == "linked_documents":
            for document in summary["linked_documents"][: _section_limit(section, 8)]:
                lines.append(f"{document['title']} ({document['category']} / {document['document_type']})")
            if not lines:
                lines.append("No linked documents")

        for line in lines[:18]:
            if y > 1530:
                break
            _png_text(draw, 68, y, line[:150], "#27314f", font_body)
            y += 22
        y += 28

    footer = str(metadata.get("footer_text") or "Generated by Jon's Gradebook")
    _png_text(draw, 52, 1560, footer[:120], "#64748b", font_body)
    image.save(image_path, format="PNG")


def generate_student_report(
    db: Session,
    student_id: int,
    basename: str = "student-report",
    include_all_rubrics: bool = True,
    rubric_id: int | None = None,
    assignment_id: int | None = None,
    template: ReportTemplate | None = None,
) -> dict[str, str]:
    settings = get_settings()
    output_root = Path(settings.storage_root) / "reports" / str(student_id)
    output_root.mkdir(parents=True, exist_ok=True)

    summary = _student_summary(
        db,
        student_id,
        include_all_rubrics=include_all_rubrics,
        rubric_id=rubric_id,
        assignment_id=assignment_id,
    )
    config = normalize_report_config(template.config_json if template else None)
    logo = _latest_logo_asset(template)

    pdf_path = output_root / f"{basename}.pdf"
    png_path = output_root / f"{basename}.png"

    _draw_pdf(pdf_path, summary, config, logo)
    _draw_png(png_path, summary, config, logo)

    return {
        "pdf_path": str(pdf_path),
        "png_path": str(png_path),
    }
