import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react'
import { api } from '../api/client'

type ReportStudent = {
  id: number
  name: string
  email?: string | null
  student_number?: string | null
}

type ReportRubric = {
  id: number
  name: string
}

type ReportAssignment = {
  id: number
  title: string
  course_id: number
}

type ReportSection = {
  key: string
  label: string
  enabled: boolean
  order: number
  options: Record<string, unknown>
}

type ReportConfig = {
  metadata: {
    report_title: string
    footer_text: string
  }
  theme: {
    primary_color: string
    accent_color: string
    neutral_color: string
    font_scale: number
    header_style: string
    logo_asset_id?: number | null
  }
  sections: ReportSection[]
}

type ReportTemplate = {
  id: number
  name: string
  description?: string | null
  report_type: string
  is_active: boolean
  is_default: boolean
  archived_at?: string | null
  config_json: ReportConfig
  logo_asset?: {
    id: number
    original_filename: string
    mime_type: string
    size_bytes: number
    url: string
  } | null
}

type ReportTargets = {
  students: ReportStudent[]
  rubrics: ReportRubric[]
  assignments: ReportAssignment[]
  templates: ReportTemplate[]
}

type ReportPreview = {
  student_id: number
  student_name: string
  student_number?: string | null
  courses: string[]
  grade_overview: { course_name: string; earned: number; possible: number; percent?: number | null }[]
  attendance: Record<string, number>
  rubric_scope: {
    include_all_rubrics: boolean
    rubric_id?: number | null
    assignment_id?: number | null
  }
  rubric_evaluations: {
    id: number
    rubric_name?: string | null
    total_points?: number | null
    max_points?: number | null
    course_name?: string | null
    assignment_title?: string | null
    created_at: string
    evaluator_notes?: string | null
    items: {
      id: number
      criterion_title: string
      criterion_type?: string | null
      criterion_max_points?: number | null
      rating_title?: string | null
      rating_description?: string | null
      points_awarded?: number | null
      is_checked?: boolean | null
      narrative_comment?: string | null
    }[]
  }[]
  recent_interactions: { type: string; summary: string; occurred_at: string }[]
  advising_meetings: { id: number; meeting_at: string; mode: string; summary?: string | null; action_items?: string | null }[]
  tasks: { id: number; title: string; status: string; priority: string; due_at?: string | null; note?: string | null }[]
  linked_documents: { id: number; title: string; category: string; document_type: string; updated_at?: string | null }[]
}

type ReportResult = {
  run_id: number
  student_id: number
  pdf_url: string
  png_url: string
  pdf_document_id: number
  png_document_id: number
  rubric_evaluation_count: number
  interaction_count: number
}

type BulkReportResult = {
  created_count: number
  artifacts: {
    run_id: number
    student_id: number
    student_name: string
    pdf_url: string
    png_url: string
    pdf_document_id: number
    png_document_id: number
  }[]
}

type ReportRun = {
  id: number
  student_id: number
  student_name: string
  template_id?: number | null
  template_name: string
  pdf_url: string
  png_url: string
  pdf_document_id?: number | null
  png_document_id?: number | null
  created_at?: string | null
}

const fallbackConfig: ReportConfig = {
  metadata: {
    report_title: 'Student Report',
    footer_text: "Generated by Jon's Gradebook",
  },
  theme: {
    primary_color: '#1b2840',
    accent_color: '#d9a441',
    neutral_color: '#f5f7fb',
    font_scale: 1,
    header_style: 'band',
    logo_asset_id: null,
  },
  sections: [
    { key: 'student_profile', label: 'Student Snapshot', enabled: true, order: 10, options: { show_email: true, show_courses: true } },
    { key: 'grade_overview', label: 'Grade Overview', enabled: true, order: 20, options: { limit: 8, show_scores: true } },
    { key: 'attendance', label: 'Attendance', enabled: true, order: 30, options: { show_empty: true } },
    { key: 'rubric_evaluations', label: 'Rubric Evaluations', enabled: true, order: 40, options: { limit: 6, item_limit: 6, show_notes: true, show_scores: true } },
    { key: 'recent_interactions', label: 'Recent Interactions', enabled: true, order: 50, options: { limit: 10 } },
    { key: 'advising_meetings', label: 'Advising Meetings', enabled: false, order: 60, options: { limit: 5, show_action_items: true } },
    { key: 'tasks', label: 'Tasks and Interventions', enabled: false, order: 70, options: { limit: 8, show_done: false } },
    { key: 'linked_documents', label: 'Linked Documents', enabled: false, order: 80, options: { limit: 8 } },
  ],
}

function cloneConfig(config: ReportConfig): ReportConfig {
  return JSON.parse(JSON.stringify(config)) as ReportConfig
}

function limitFor(section: ReportSection, fallback: number) {
  const raw = section.options?.limit
  const parsed = typeof raw === 'number' ? raw : Number(raw)
  return Number.isFinite(parsed) ? Math.max(1, parsed) : fallback
}

function scoreLabel(value?: number | null, max?: number | null) {
  if (value !== null && value !== undefined && max !== null && max !== undefined) return `${value} / ${max}`
  if (value !== null && value !== undefined) return String(value)
  return 'N/A'
}

export function ReportsPage() {
  const [targets, setTargets] = useState<ReportTargets | null>(null)
  const [templates, setTemplates] = useState<ReportTemplate[]>([])
  const [runs, setRuns] = useState<ReportRun[]>([])
  const [studentId, setStudentId] = useState('')
  const [templateId, setTemplateId] = useState('')
  const [includeAllRubrics, setIncludeAllRubrics] = useState(true)
  const [rubricId, setRubricId] = useState('')
  const [assignmentId, setAssignmentId] = useState('')

  const [editName, setEditName] = useState('')
  const [editDescription, setEditDescription] = useState('')
  const [editConfig, setEditConfig] = useState<ReportConfig>(cloneConfig(fallbackConfig))
  const [isDirty, setIsDirty] = useState(false)

  const [preview, setPreview] = useState<ReportPreview | null>(null)
  const [reportResult, setReportResult] = useState<ReportResult | null>(null)
  const [bulkResult, setBulkResult] = useState<BulkReportResult | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [isSaving, setIsSaving] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)

  const selectedTemplate = useMemo(
    () => templates.find((template) => String(template.id) === templateId) || null,
    [templates, templateId]
  )
  const selectedStudent = useMemo(
    () => targets?.students.find((student) => String(student.id) === studentId) || null,
    [targets, studentId]
  )
  const sortedSections = useMemo(
    () => [...editConfig.sections].sort((a, b) => a.order - b.order || a.label.localeCompare(b.label)),
    [editConfig.sections]
  )

  async function loadTargets() {
    const rows = await api.get<ReportTargets>('/reports/targets')
    setTargets(rows)
    setTemplates(rows.templates)
    if (!studentId && rows.students.length > 0) {
      setStudentId(String(rows.students[0].id))
    }
    if (!templateId && rows.templates.length > 0) {
      const defaultTemplate = rows.templates.find((template) => template.is_default) || rows.templates[0]
      setTemplateId(String(defaultTemplate.id))
    }
  }

  async function loadTemplates() {
    const rows = await api.get<ReportTemplate[]>('/reports/templates')
    setTemplates(rows)
    setTargets((current) => (current ? { ...current, templates: rows } : current))
  }

  async function loadRuns() {
    const rows = await api.get<ReportRun[]>('/reports/runs')
    setRuns(rows)
  }

  async function loadPreview(targetStudentId: string, targetTemplateId: string) {
    if (!targetStudentId || !targetTemplateId) return

    const params = new URLSearchParams()
    params.set('template_id', targetTemplateId)
    params.set('include_all_rubrics', includeAllRubrics ? 'true' : 'false')
    if (!includeAllRubrics && rubricId) params.set('rubric_id', rubricId)
    if (!includeAllRubrics && assignmentId) params.set('assignment_id', assignmentId)

    const response = await api.get<ReportPreview>(`/reports/students/${targetStudentId}/preview?${params.toString()}`)
    setPreview(response)
  }

  useEffect(() => {
    void Promise.all([loadTargets(), loadRuns()]).catch((err) => setError((err as Error).message))
  }, [])

  useEffect(() => {
    if (selectedTemplate) {
      setEditName(selectedTemplate.name)
      setEditDescription(selectedTemplate.description || '')
      setEditConfig(cloneConfig(selectedTemplate.config_json || fallbackConfig))
      setIsDirty(false)
    }
  }, [selectedTemplate?.id])

  useEffect(() => {
    if (studentId && templateId) {
      void loadPreview(studentId, templateId).catch((err) => setError((err as Error).message))
    }
  }, [studentId, templateId, includeAllRubrics, rubricId, assignmentId])

  function markConfig(next: ReportConfig) {
    setEditConfig(next)
    setIsDirty(true)
  }

  function updateMetadata(field: keyof ReportConfig['metadata'], value: string) {
    markConfig({ ...editConfig, metadata: { ...editConfig.metadata, [field]: value } })
  }

  function updateTheme(field: keyof ReportConfig['theme'], value: string | number) {
    markConfig({ ...editConfig, theme: { ...editConfig.theme, [field]: value } })
  }

  function updateSection(sectionKey: string, patch: Partial<ReportSection>) {
    markConfig({
      ...editConfig,
      sections: editConfig.sections.map((section) => (section.key === sectionKey ? { ...section, ...patch } : section)),
    })
  }

  function updateSectionOption(sectionKey: string, optionKey: string, value: unknown) {
    markConfig({
      ...editConfig,
      sections: editConfig.sections.map((section) =>
        section.key === sectionKey
          ? { ...section, options: { ...section.options, [optionKey]: value } }
          : section
      ),
    })
  }

  function moveSection(sectionKey: string, direction: -1 | 1) {
    const sections = [...sortedSections]
    const index = sections.findIndex((section) => section.key === sectionKey)
    const nextIndex = index + direction
    if (index < 0 || nextIndex < 0 || nextIndex >= sections.length) return
    const [section] = sections.splice(index, 1)
    sections.splice(nextIndex, 0, section)
    markConfig({ ...editConfig, sections: sections.map((item, orderIndex) => ({ ...item, order: (orderIndex + 1) * 10 })) })
  }

  async function saveTemplate(): Promise<ReportTemplate | null> {
    if (!selectedTemplate) return null
    setIsSaving(true)
    setError(null)
    try {
      const saved = await api.patch<ReportTemplate>(`/reports/templates/${selectedTemplate.id}`, {
        name: editName.trim() || selectedTemplate.name,
        description: editDescription.trim() || null,
        config_json: editConfig,
      })
      await loadTemplates()
      setTemplateId(String(saved.id))
      setIsDirty(false)
      return saved
    } catch (err) {
      setError((err as Error).message)
      return null
    } finally {
      setIsSaving(false)
    }
  }

  async function createTemplate() {
    setIsSaving(true)
    setError(null)
    try {
      const created = await api.post<ReportTemplate>('/reports/templates', {
        name: 'Custom Student Report',
        description: 'Editable student report template.',
        config_json: editConfig,
      })
      await loadTemplates()
      setTemplateId(String(created.id))
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setIsSaving(false)
    }
  }

  async function duplicateTemplate() {
    if (!selectedTemplate) return
    setIsSaving(true)
    setError(null)
    try {
      const duplicated = await api.post<ReportTemplate>(`/reports/templates/${selectedTemplate.id}/duplicate`)
      await loadTemplates()
      setTemplateId(String(duplicated.id))
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setIsSaving(false)
    }
  }

  async function archiveTemplate() {
    if (!selectedTemplate) return
    setIsSaving(true)
    setError(null)
    try {
      await api.patch<ReportTemplate>(`/reports/templates/${selectedTemplate.id}`, { archived: true })
      const rows = await api.get<ReportTemplate[]>('/reports/templates')
      setTemplates(rows)
      setTargets((current) => (current ? { ...current, templates: rows } : current))
      if (rows.length > 0) setTemplateId(String(rows[0].id))
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setIsSaving(false)
    }
  }

  async function makeDefaultTemplate() {
    if (!selectedTemplate) return
    setIsSaving(true)
    setError(null)
    try {
      await api.patch<ReportTemplate>(`/reports/templates/${selectedTemplate.id}`, { is_default: true })
      await loadTemplates()
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setIsSaving(false)
    }
  }

  async function uploadLogo(event: ChangeEvent<HTMLInputElement>) {
    if (!selectedTemplate || !event.target.files?.[0]) return
    const form = new FormData()
    form.append('file', event.target.files[0])
    setIsSaving(true)
    setError(null)
    try {
      const updated = await api.post<ReportTemplate>(`/reports/templates/${selectedTemplate.id}/assets/logo`, form)
      await loadTemplates()
      setTemplateId(String(updated.id))
    } catch (err) {
      setError((err as Error).message)
    } finally {
      event.target.value = ''
      setIsSaving(false)
    }
  }

  async function generate(event: FormEvent) {
    event.preventDefault()
    if (!studentId || !selectedTemplate) return

    setIsGenerating(true)
    setError(null)
    setBulkResult(null)

    try {
      const savedTemplate = isDirty ? await saveTemplate() : selectedTemplate
      if (!savedTemplate) return
      const payload = {
        template_id: savedTemplate.id,
        include_all_rubrics: includeAllRubrics,
        rubric_id: includeAllRubrics || !rubricId ? null : Number(rubricId),
        assignment_id: includeAllRubrics || !assignmentId ? null : Number(assignmentId),
      }
      const response = await api.post<ReportResult>(`/reports/students/${studentId}`, payload)
      setReportResult(response)
      await Promise.all([loadPreview(studentId, String(savedTemplate.id)), loadRuns()])
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setIsGenerating(false)
    }
  }

  async function generateAllStudentsAllRubrics() {
    if (!selectedTemplate) return
    setIsGenerating(true)
    setError(null)
    try {
      const savedTemplate = isDirty ? await saveTemplate() : selectedTemplate
      if (!savedTemplate) return
      const response = await api.post<BulkReportResult>('/reports/students/bulk', {
        template_id: savedTemplate.id,
        include_all_rubrics: true,
      })
      setBulkResult(response)
      await loadRuns()
    } catch (err) {
      setError((err as Error).message)
    } finally {
      setIsGenerating(false)
    }
  }

  function renderPreviewSection(section: ReportSection) {
    if (!preview) return null
    if (section.key === 'student_profile') {
      return (
        <div className="report-preview-lines">
          <span>Email: {selectedStudent?.email || 'N/A'}</span>
          <span>Student number: {preview.student_number || selectedStudent?.student_number || 'N/A'}</span>
          <span>Courses: {preview.courses.length > 0 ? preview.courses.join(', ') : 'None'}</span>
        </div>
      )
    }
    if (section.key === 'grade_overview') {
      const rows = preview.grade_overview.slice(0, limitFor(section, 8))
      return rows.length > 0 ? (
        <div className="report-preview-table">
          {rows.map((row) => (
            <div key={row.course_name}>
              <strong>{row.course_name}</strong>
              <span>{section.options.show_scores !== false ? `${row.earned} / ${row.possible}` : `${row.percent ?? 'N/A'}%`}</span>
              <span>{row.percent !== null && row.percent !== undefined ? `${row.percent}%` : 'N/A'}</span>
            </div>
          ))}
        </div>
      ) : (
        <p className="subtitle">No grade data available.</p>
      )
    }
    if (section.key === 'attendance') {
      return (
        <div className="report-stat-row">
          {['present', 'absent', 'tardy', 'excused'].map((status) => (
            <span key={status}><strong>{preview.attendance[status] || 0}</strong>{status}</span>
          ))}
        </div>
      )
    }
    if (section.key === 'rubric_evaluations') {
      const rows = preview.rubric_evaluations.slice(0, limitFor(section, 6))
      return rows.length > 0 ? (
        <div className="rubric-report-stack">
          {rows.map((evaluation) => (
            <section key={evaluation.id} className="rubric-report-block">
              <header className="rubric-report-header">
                <div>
                  <strong>{evaluation.rubric_name || 'Rubric'}</strong>
                  <span>{evaluation.assignment_title || evaluation.course_name || 'General'}</span>
                </div>
                {section.options.show_scores !== false ? (
                  <div className="rubric-score-pill">{scoreLabel(evaluation.total_points, evaluation.max_points)}</div>
                ) : null}
              </header>
              <div className="rubric-report-meta">{evaluation.created_at.slice(0, 10)}</div>
              <div className="rubric-report-grid">
                {evaluation.items.slice(0, Number(section.options.item_limit || 6)).map((item) => (
                  <div key={item.id} className="rubric-report-row">
                    <div>
                      <strong>{item.criterion_title}</strong>
                      <span>{item.criterion_type || 'criterion'}</span>
                    </div>
                    <div>
                      <strong>{item.rating_title || (item.is_checked ? 'Checked' : 'No rating')}</strong>
                      <span>{item.rating_description || item.narrative_comment || 'No additional feedback'}</span>
                    </div>
                    {section.options.show_scores !== false ? (
                      <div className="rubric-report-points">{scoreLabel(item.points_awarded, item.criterion_max_points)}</div>
                    ) : null}
                  </div>
                ))}
              </div>
              {section.options.show_notes !== false && evaluation.evaluator_notes ? <p className="rubric-report-notes">{evaluation.evaluator_notes}</p> : null}
            </section>
          ))}
        </div>
      ) : (
        <p className="subtitle">No rubric evaluations for current scope.</p>
      )
    }
    if (section.key === 'recent_interactions') {
      const rows = preview.recent_interactions.slice(0, limitFor(section, 10))
      return rows.length > 0 ? (
        <div className="report-preview-list">
          {rows.map((interaction, index) => (
            <div key={`${interaction.occurred_at}-${index}`}>
              <strong>{interaction.occurred_at.slice(0, 10)} [{interaction.type}]</strong>
              <span>{interaction.summary}</span>
            </div>
          ))}
        </div>
      ) : <p className="subtitle">No recent interactions.</p>
    }
    if (section.key === 'advising_meetings') {
      const rows = preview.advising_meetings.slice(0, limitFor(section, 5))
      return rows.length > 0 ? (
        <div className="report-preview-list">
          {rows.map((meeting) => (
            <div key={meeting.id}>
              <strong>{meeting.meeting_at.slice(0, 10)} · {meeting.mode.replace('_', ' ')}</strong>
              <span>{meeting.summary || 'No summary'}</span>
              {section.options.show_action_items !== false && meeting.action_items ? <span>Actions: {meeting.action_items}</span> : null}
            </div>
          ))}
        </div>
      ) : <p className="subtitle">No advising meetings linked to this student.</p>
    }
    if (section.key === 'tasks') {
      const rows = preview.tasks.filter((task) => section.options.show_done === true || task.status !== 'done').slice(0, limitFor(section, 8))
      return rows.length > 0 ? (
        <div className="report-preview-list">
          {rows.map((task) => (
            <div key={task.id}>
              <strong>{task.title}</strong>
              <span>{task.priority} · {task.status}{task.due_at ? ` · due ${task.due_at.slice(0, 10)}` : ''}</span>
            </div>
          ))}
        </div>
      ) : <p className="subtitle">No matching tasks.</p>
    }
    if (section.key === 'linked_documents') {
      const rows = preview.linked_documents.slice(0, limitFor(section, 8))
      return rows.length > 0 ? (
        <div className="report-preview-list">
          {rows.map((document) => (
            <div key={document.id}>
              <strong>{document.title}</strong>
              <span>{document.category} · {document.document_type}</span>
            </div>
          ))}
        </div>
      ) : <p className="subtitle">No linked documents.</p>
    }
    return <p className="subtitle">Section preview unavailable.</p>
  }

  return (
    <section>
      <div className="page-heading-row">
        <div>
          <h2>Report Builder</h2>
          <p className="subtitle">Design student report templates, preview with live student data, and export PDF/PNG artifacts into Reports and Documents.</p>
        </div>
        <div className="chip-row">
          {isDirty ? <span className="chip">Unsaved changes</span> : <span className="chip">Saved</span>}
          {selectedTemplate?.is_default ? <span className="chip">Default</span> : null}
        </div>
      </div>

      <div className="report-builder-shell">
        <aside className="report-template-rail">
          <div className="rail-header">
            <h3>Templates</h3>
            <button type="button" onClick={() => void createTemplate()} disabled={isSaving}>New</button>
          </div>
          <div className="report-template-list">
            {templates.map((template) => (
              <button
                type="button"
                key={template.id}
                className={String(template.id) === templateId ? 'report-template-item active' : 'report-template-item'}
                onClick={() => setTemplateId(String(template.id))}
              >
                <strong>{template.name}</strong>
                <span>{template.description || 'No description'}</span>
              </button>
            ))}
          </div>

          <form className="form report-generate-form" onSubmit={generate}>
            <h3>Generate</h3>
            <select value={studentId} onChange={(event) => setStudentId(event.target.value)} required>
              <option value="">Select student...</option>
              {targets?.students.map((student) => (
                <option key={student.id} value={student.id}>
                  {student.name}
                  {student.student_number ? ` #${student.student_number}` : ''}
                  {student.email ? ` (${student.email})` : ''}
                </option>
              ))}
            </select>
            <label>
              <input
                type="checkbox"
                checked={includeAllRubrics}
                onChange={(event) => setIncludeAllRubrics(event.target.checked)}
              />
              Include all rubrics
            </label>
            {!includeAllRubrics ? (
              <>
                <select value={rubricId} onChange={(event) => setRubricId(event.target.value)}>
                  <option value="">Any rubric</option>
                  {targets?.rubrics.map((rubric) => (
                    <option key={rubric.id} value={rubric.id}>{rubric.name}</option>
                  ))}
                </select>
                <select value={assignmentId} onChange={(event) => setAssignmentId(event.target.value)}>
                  <option value="">Any assignment</option>
                  {targets?.assignments.map((assignment) => (
                    <option key={assignment.id} value={assignment.id}>{assignment.title}</option>
                  ))}
                </select>
              </>
            ) : null}
            <button type="submit" disabled={isGenerating || !studentId || !selectedTemplate}>
              {isGenerating ? 'Generating...' : 'Generate Report'}
            </button>
            <button type="button" onClick={() => void generateAllStudentsAllRubrics()} disabled={isGenerating || !selectedTemplate}>
              {isGenerating ? 'Running...' : 'Bulk Generate'}
            </button>
          </form>
        </aside>

        <main className="report-preview-pane">
          <div
            className={editConfig.theme.header_style === 'band' ? 'report-preview-page banded' : 'report-preview-page'}
            style={{
              background: editConfig.theme.neutral_color,
              ['--report-primary' as string]: editConfig.theme.primary_color,
              ['--report-accent' as string]: editConfig.theme.accent_color,
              ['--report-scale' as string]: String(editConfig.theme.font_scale || 1),
            }}
          >
            <header className="report-preview-cover">
              {selectedTemplate?.logo_asset ? <img src={selectedTemplate.logo_asset.url} alt="" /> : <div className="report-logo-placeholder">JG</div>}
              <div>
                <h3>{editConfig.metadata.report_title || editName || 'Student Report'}</h3>
                <p>{preview?.student_name || selectedStudent?.name || 'Select a student'}</p>
              </div>
            </header>

            {preview ? (
              sortedSections.filter((section) => section.enabled).map((section) => (
                <section key={section.key} className="report-preview-section">
                  <h4>{section.label}</h4>
                  {renderPreviewSection(section)}
                </section>
              ))
            ) : (
              <div className="report-preview-empty">Choose a student and template to preview the report.</div>
            )}

            <footer>{editConfig.metadata.footer_text}</footer>
          </div>
        </main>

        <aside className="report-inspector">
          <div className="inspector-actions">
            <button type="button" onClick={() => void saveTemplate()} disabled={isSaving || !selectedTemplate}>
              {isSaving ? 'Saving...' : 'Save'}
            </button>
            <button type="button" onClick={() => void duplicateTemplate()} disabled={isSaving || !selectedTemplate}>Duplicate</button>
            <button type="button" onClick={() => void makeDefaultTemplate()} disabled={isSaving || !selectedTemplate || selectedTemplate.is_default}>Make Default</button>
            <button type="button" onClick={() => void archiveTemplate()} disabled={isSaving || !selectedTemplate || templates.length <= 1}>Archive</button>
          </div>

          <div className="form inspector-form">
            <h3>Template</h3>
            <input value={editName} onChange={(event) => { setEditName(event.target.value); setIsDirty(true) }} placeholder="Template name" />
            <textarea value={editDescription} onChange={(event) => { setEditDescription(event.target.value); setIsDirty(true) }} placeholder="Description" />
            <input value={editConfig.metadata.report_title} onChange={(event) => updateMetadata('report_title', event.target.value)} placeholder="Report title" />
            <input value={editConfig.metadata.footer_text} onChange={(event) => updateMetadata('footer_text', event.target.value)} placeholder="Footer text" />

            <h3>Branding</h3>
            <div className="report-color-grid">
              <label>Primary<input type="color" value={editConfig.theme.primary_color} onChange={(event) => updateTheme('primary_color', event.target.value)} /></label>
              <label>Accent<input type="color" value={editConfig.theme.accent_color} onChange={(event) => updateTheme('accent_color', event.target.value)} /></label>
              <label>Paper<input type="color" value={editConfig.theme.neutral_color} onChange={(event) => updateTheme('neutral_color', event.target.value)} /></label>
            </div>
            <label>
              Scale
              <input
                type="range"
                min="0.85"
                max="1.25"
                step="0.05"
                value={editConfig.theme.font_scale}
                onChange={(event) => updateTheme('font_scale', Number(event.target.value))}
              />
            </label>
            <select value={editConfig.theme.header_style} onChange={(event) => updateTheme('header_style', event.target.value)}>
              <option value="band">Band header</option>
              <option value="plain">Plain header</option>
            </select>
            <label className="file-button">
              Upload Logo
              <input type="file" accept="image/*" onChange={(event) => void uploadLogo(event)} />
            </label>

            <h3>Sections</h3>
            <div className="report-section-editor-list">
              {sortedSections.map((section, index) => (
                <div key={section.key} className={section.enabled ? 'report-section-editor' : 'report-section-editor disabled'}>
                  <div className="section-editor-topline">
                    <label>
                      <input type="checkbox" checked={section.enabled} onChange={(event) => updateSection(section.key, { enabled: event.target.checked })} />
                      {section.key.replace(/_/g, ' ')}
                    </label>
                    <div>
                      <button type="button" onClick={() => moveSection(section.key, -1)} disabled={index === 0}>Up</button>
                      <button type="button" onClick={() => moveSection(section.key, 1)} disabled={index === sortedSections.length - 1}>Down</button>
                    </div>
                  </div>
                  <input value={section.label} onChange={(event) => updateSection(section.key, { label: event.target.value })} />
                  <div className="section-option-row">
                    <label>
                      Limit
                      <input
                        type="number"
                        min="1"
                        max="50"
                        value={Number(section.options.limit || 6)}
                        onChange={(event) => updateSectionOption(section.key, 'limit', Number(event.target.value))}
                      />
                    </label>
                    {section.key === 'rubric_evaluations' ? (
                      <label>
                        Items
                        <input
                          type="number"
                          min="1"
                          max="20"
                          value={Number(section.options.item_limit || 6)}
                          onChange={(event) => updateSectionOption(section.key, 'item_limit', Number(event.target.value))}
                        />
                      </label>
                    ) : null}
                  </div>
                  <div className="section-toggle-row">
                    {['show_scores', 'show_notes', 'show_action_items', 'show_done'].map((option) => (
                      option in section.options ? (
                        <label key={option}>
                          <input
                            type="checkbox"
                            checked={section.options[option] !== false}
                            onChange={(event) => updateSectionOption(section.key, option, event.target.checked)}
                          />
                          {option.replace('show_', '').replace('_', ' ')}
                        </label>
                      ) : null
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </aside>
      </div>

      {reportResult ? (
        <article className="card" style={{ marginTop: '0.8rem' }}>
          <h3>Latest Export</h3>
          <div>Student: {selectedStudent?.name || reportResult.student_id}</div>
          <div>PDF: <a href={reportResult.pdf_url} target="_blank" rel="noreferrer">Download PDF</a> · Document #{reportResult.pdf_document_id}</div>
          <div>PNG: <a href={reportResult.png_url} target="_blank" rel="noreferrer">Download PNG</a> · Document #{reportResult.png_document_id}</div>
          <div>Rubric evaluations included: {reportResult.rubric_evaluation_count}</div>
          <div>Recent interactions included: {reportResult.interaction_count}</div>
        </article>
      ) : null}

      {bulkResult ? (
        <article className="card" style={{ marginTop: '0.8rem' }}>
          <h3>Bulk Export Results</h3>
          <div>Created reports: {bulkResult.created_count}</div>
          <div className="students-grid-wrap" style={{ marginTop: '0.5rem' }}>
            <table className="students-grid-table">
              <thead>
                <tr>
                  <th>Student</th>
                  <th>PDF</th>
                  <th>PNG</th>
                  <th>Documents</th>
                </tr>
              </thead>
              <tbody>
                {bulkResult.artifacts.map((artifact) => (
                  <tr key={artifact.run_id}>
                    <td>{artifact.student_name}</td>
                    <td><a href={artifact.pdf_url} target="_blank" rel="noreferrer">Download PDF</a></td>
                    <td><a href={artifact.png_url} target="_blank" rel="noreferrer">Download PNG</a></td>
                    <td>#{artifact.pdf_document_id}, #{artifact.png_document_id}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </article>
      ) : null}

      <article className="card" style={{ marginTop: '0.8rem' }}>
        <h3>Report History</h3>
        {runs.length > 0 ? (
          <div className="students-grid-wrap">
            <table className="students-grid-table">
              <thead>
                <tr>
                  <th>Created</th>
                  <th>Student</th>
                  <th>Template</th>
                  <th>Exports</th>
                  <th>Documents</th>
                </tr>
              </thead>
              <tbody>
                {runs.map((run) => (
                  <tr key={run.id}>
                    <td>{run.created_at ? run.created_at.slice(0, 16).replace('T', ' ') : 'N/A'}</td>
                    <td>{run.student_name}</td>
                    <td>{run.template_name}</td>
                    <td><a href={run.pdf_url} target="_blank" rel="noreferrer">PDF</a> · <a href={run.png_url} target="_blank" rel="noreferrer">PNG</a></td>
                    <td>{run.pdf_document_id ? `#${run.pdf_document_id}` : 'N/A'} · {run.png_document_id ? `#${run.png_document_id}` : 'N/A'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p className="subtitle">No reports generated yet.</p>
        )}
      </article>

      {error ? <p className="error">{error}</p> : null}
    </section>
  )
}
