import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { App } from './App'

function jsonResponse(payload: unknown): Response {
  return {
    ok: true,
    status: 200,
    json: async () => payload,
    text: async () => JSON.stringify(payload),
  } as Response
}

function mockApiFetch() {
  return vi.fn(async (input: RequestInfo | URL) => {
    const url = String(input)

    if (url.includes('/api/v1/dashboard/summary')) {
      return jsonResponse({
        cards: {
          needs_grading: 2,
          missing_late_followup: 4,
          out_of_sync_overrides: 1,
          unread_alerts: 0,
          upcoming_advising_followups: 3,
        },
        top_risk_students: [],
        latest_sync: null,
      })
    }

    if (url.includes('/api/v1/tasks/targets')) {
      return jsonResponse({ students: [], courses: [] })
    }

    if (url.includes('/api/v1/tasks/?')) {
      return jsonResponse([
        {
          id: 77,
          title: 'Follow up with Ada',
          status: 'open',
          priority: 'high',
          due_at: null,
          note: 'Risk reasons: missing work',
          linked_student_id: null,
          linked_course_id: null,
          linked_interaction_id: null,
          linked_advising_meeting_id: null,
          source: 'rule_engine',
          outcome_tag: null,
          outcome_note: null,
          created_at: '2026-04-24T12:00:00',
          updated_at: '2026-04-24T12:00:00',
        },
      ])
    }

    if (url.includes('/api/v1/canvas/sync/runs/1/conflicts')) {
      return jsonResponse([
        {
          id: 88,
          sync_run_id: 1,
          course_name: 'Biology 101',
          assignment_title: 'Lab Report',
          student_name: 'Ada Lovelace',
          local: { score: 7, status: 'graded', source: 'manual_override' },
          canvas: { score: 9, status: 'graded' },
          status: 'pending',
          rationale: null,
          created_at: '2026-04-24T12:00:00',
        },
      ])
    }

    if (url.includes('/api/v1/canvas/sync/runs/1/diff')) {
      return jsonResponse({
        run_id: 1,
        previous_run_id: null,
        entity_type: 'submission',
        rows: [
          {
            identity: 'course-1:assignment-1:user-1',
            change_type: 'created',
            changed_fields: [],
            before: null,
            after: { canvas_course_id: 'course-1', score: 9 },
          },
        ],
      })
    }

    if (url.includes('/api/v1/canvas/sync/runs/1/events')) {
      return jsonResponse({ total: 0, offset: 0, limit: 50, events: [] })
    }

    if (url.endsWith('/api/v1/canvas/sync/runs/1')) {
      return jsonResponse({
        id: 1,
        snapshot_counts: { courses: 1, assignments: 1, enrollments: 1, submissions: 1 },
        event_counts: { created: 1, updated: 0, deleted: 0 },
        recent_events: [],
      })
    }

    if (url.includes('/api/v1/canvas/sync/runs')) {
      return jsonResponse([
        {
          id: 1,
          trigger_type: 'manual',
          status: 'completed',
          started_at: '2026-04-24T12:00:00',
          finished_at: '2026-04-24T12:01:00',
          event_counts: { created: 1, updated: 0, deleted: 0 },
        },
      ])
    }

    if (url.includes('/api/v1/canvas/courses/discover')) {
      return jsonResponse([{ canvas_course_id: 'course-1', name: 'Biology 101', is_selected: true }])
    }

    if (url.includes('/api/v1/canvas/student-metadata/mapping')) {
      return jsonResponse({
        mappings: [
          { target_field: 'first_name', source_paths: ['user.first_name'], default_source_paths: ['user.first_name'] },
        ],
        common_source_paths: ['user.first_name'],
      })
    }

    if (url.includes('/api/v1/canvas/student-metadata/preview')) {
      return jsonResponse({ canvas_course_id: 'course-1', sample_count: 0, labels: [], rows: [] })
    }

    if (url.includes('/api/v1/documents/targets')) {
      return jsonResponse({ students: [{ id: 42, name: 'Ada Lovelace', email: 'ada@example.edu' }] })
    }

    if (url.includes('/api/v1/reports/targets')) {
      return jsonResponse({
        students: [{ id: 42, name: 'Ada Lovelace', email: 'ada@example.edu', student_number: 'S-42' }],
        rubrics: [{ id: 3, name: 'Research Rubric' }],
        assignments: [{ id: 9, title: 'Lab Report', course_id: 1 }],
        templates: [
          {
            id: 5,
            name: 'Progress Snapshot',
            description: 'Balanced report.',
            report_type: 'student',
            is_active: true,
            is_default: true,
            archived_at: null,
            logo_asset: null,
            config_json: {
              metadata: { report_title: 'Progress Snapshot', footer_text: "Generated by Jon's Gradebook" },
              theme: {
                primary_color: '#1b2840',
                accent_color: '#d9a441',
                neutral_color: '#f5f7fb',
                font_scale: 1,
                header_style: 'band',
                logo_asset_id: null,
              },
              sections: [
                { key: 'student_profile', label: 'Student Snapshot', enabled: true, order: 10, options: { show_email: true, show_courses: true } },
                { key: 'grade_overview', label: 'Grade Overview', enabled: true, order: 20, options: { limit: 8, show_scores: true } },
                { key: 'attendance', label: 'Attendance', enabled: true, order: 30, options: { show_empty: true } },
                { key: 'rubric_evaluations', label: 'Rubric Evaluations', enabled: true, order: 40, options: { limit: 6, item_limit: 6, show_notes: true, show_scores: true } },
                { key: 'recent_interactions', label: 'Recent Interactions', enabled: true, order: 50, options: { limit: 10 } },
                { key: 'advising_meetings', label: 'Advising Meetings', enabled: false, order: 60, options: { limit: 5, show_action_items: true } },
                { key: 'tasks', label: 'Tasks and Interventions', enabled: false, order: 70, options: { limit: 8, show_done: false } },
                { key: 'linked_documents', label: 'Linked Documents', enabled: false, order: 80, options: { limit: 8 } },
              ],
            },
          },
        ],
      })
    }

    if (url.includes('/api/v1/reports/runs')) {
      return jsonResponse([])
    }

    if (url.includes('/api/v1/llm/targets')) {
      return jsonResponse({
        students: [{ id: 42, name: 'Ada Lovelace', email: 'ada@example.edu', student_number: 'S-42' }],
        documents: [
          {
            id: 99,
            title: 'Paper Draft',
            category: 'Student Work',
            document_type: 'txt',
            owner_type: 'student',
            owner_id: 42,
            linked_student_ids: [42],
            updated_at: '2026-04-24T12:00:00',
          },
        ],
        rubrics: [{ id: 3, name: 'Research Rubric', description: 'Research writing', max_points: 10 }],
        providers: [
          { value: 'ollama', label: 'Ollama', default_model: 'llama3.1', local: true },
          { value: 'openai', label: 'OpenAI', default_model: 'gpt-5-mini', local: false },
        ],
      })
    }

    if (url.includes('/api/v1/llm/instructions')) {
      return jsonResponse([
        {
          id: 12,
          name: 'Paper Feedback',
          description: 'Balanced feedback.',
          task_type: 'feedback',
          instructions: 'Read the paper and provide feedback.',
          output_guidance: 'Use sections.',
          rubric_guidance: 'Do not score.',
          is_active: true,
          is_default: true,
          archived_at: null,
        },
      ])
    }

    if (url.includes('/api/v1/llm/workbench/jobs')) {
      return jsonResponse([
        {
          id: 21,
          student_profile_id: 42,
          student_name: 'Ada Lovelace',
          source_document_id: 99,
          source_document_title: 'Paper Draft',
          instruction_template_id: 12,
          instruction_template_name: 'Paper Feedback',
          rubric_id: null,
          rubric_name: null,
          final_document_id: null,
          provider: 'ollama',
          model: 'llama3.1',
          status: 'prompt_ready',
          final_feedback: '',
          metadata_json: {},
          run: {
            id: 33,
            preview: 'TRUSTED INSTRUCTIONS\n\nUNTRUSTED STUDENT WORK TO ANALYZE',
            deidentify_map: { '[NAME_1]': 'Ada Lovelace' },
            outputs: [],
          },
        },
      ])
    }

    if (url.includes('/api/v1/reports/students/42/preview')) {
      return jsonResponse({
        student_id: 42,
        student_name: 'Ada Lovelace',
        student_number: 'S-42',
        courses: ['Biology 101'],
        grade_overview: [{ course_name: 'Biology 101', earned: 8, possible: 10, percent: 80 }],
        attendance: { present: 1, absent: 0, tardy: 0, excused: 0 },
        rubric_scope: { include_all_rubrics: true, rubric_id: null, assignment_id: null },
        rubric_evaluations: [
          {
            id: 7,
            rubric_name: 'Research Rubric',
            total_points: 8,
            max_points: 10,
            course_name: 'Biology 101',
            assignment_title: 'Lab Report',
            created_at: '2026-04-24T12:00:00',
            evaluator_notes: 'Strong evidence.',
            items: [
              {
                id: 11,
                criterion_title: 'Evidence',
                criterion_type: 'points',
                criterion_max_points: 5,
                rating_title: 'Proficient',
                rating_description: 'Uses relevant observations.',
                points_awarded: 4,
                is_checked: null,
                narrative_comment: null,
              },
            ],
          },
        ],
        recent_interactions: [],
        advising_meetings: [],
        tasks: [],
        linked_documents: [],
      })
    }

    if (url.includes('/api/v1/rubrics/evaluations?student_profile_id=42')) {
      return jsonResponse([
        {
          id: 7,
          rubric_id: 3,
          rubric_name: 'Research Rubric',
          rubric_max_points: 10,
          student_profile_id: 42,
          course_id: 1,
          course_name: 'Biology 101',
          assignment_id: 9,
          assignment_title: 'Lab Report',
          evaluator_notes: 'Strong evidence.',
          total_points: 8,
          created_at: '2026-04-24T12:00:00',
          items: [
            {
              id: 11,
              criterion_id: 5,
              criterion_title: 'Evidence',
              criterion_type: 'points',
              criterion_max_points: 5,
              rating_id: 6,
              rating_title: 'Proficient',
              rating_description: 'Uses relevant observations.',
              points_awarded: 4,
              is_checked: null,
              narrative_comment: null,
            },
          ],
        },
      ])
    }

    if (url.includes('/api/v1/students/42/profile')) {
      return jsonResponse({
        student: {
          id: 42,
          name: 'Ada Lovelace',
          first_name: 'Ada',
          last_name: 'Lovelace',
          email: 'ada@example.edu',
          phone_number: null,
          student_number: 'S-42',
          notes: 'Enjoys proofs.',
          is_advisee: false,
          advisee_id: null,
        },
        priority_sections: ['alerts', 'attendance_summary', 'recent_interactions', 'grade_overview'],
        alerts: [],
        flags_tags: [],
        attendance_summary: { present: 1, absent: 0, tardy: 0, excused: 0, total_records: 1 },
        courses: [
          {
            course_id: 1,
            name: 'Biology 101',
            section_name: 'A',
            totals: { earned: 8, possible: 10, percent: 80 },
            assignments: [
              {
                assignment_id: 9,
                title: 'Lab Report',
                source: 'local',
                due_at: null,
                points_possible: 10,
                score: 8,
                status: 'graded',
                percent: 80,
              },
            ],
          },
        ],
        grade_overview: [{ course_id: 1, course_name: 'Biology 101', earned: 8, possible: 10, percent: 80 }],
        student_documents: [],
        recent_interactions: [],
        advising_meetings: [],
      })
    }

    if (url.includes('/api/v1/courses/1/matches/history')) {
      return jsonResponse([])
    }

    if (url.includes('/api/v1/courses/1/matches')) {
      return jsonResponse([])
    }

    if (url.endsWith('/api/v1/courses/')) {
      return jsonResponse([{ id: 1, name: 'Biology 101', section_name: 'A' }])
    }

    return jsonResponse({})
  })
}

describe('App smoke routes', () => {
  beforeEach(() => {
    vi.stubGlobal('fetch', mockApiFetch())
  })

  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it('renders action dashboard on root route', async () => {
    render(
      <MemoryRouter initialEntries={['/']}>
        <App />
      </MemoryRouter>,
    )

    expect(await screen.findByText('Action Dashboard')).toBeInTheDocument()
    expect(await screen.findByText('Needs Grading / Match Review')).toBeInTheDocument()
  })

  it('renders task queue route', async () => {
    render(
      <MemoryRouter initialEntries={['/tasks']}>
        <App />
      </MemoryRouter>,
    )

    expect(await screen.findByText('Task Queue')).toBeInTheDocument()
    expect(await screen.findByText('Run Intervention Rules')).toBeInTheDocument()
    expect(await screen.findByText('Follow up with Ada')).toBeInTheDocument()
  })

  it('switches task queue into board view', async () => {
    const user = userEvent.setup()
    render(
      <MemoryRouter initialEntries={['/tasks']}>
        <App />
      </MemoryRouter>,
    )

    await user.click(await screen.findByText('Board View'))
    expect(await screen.findByText('open')).toBeInTheDocument()
    expect(await screen.findByText('Follow up with Ada')).toBeInTheDocument()
  })

  it('renders Canvas conflict and snapshot diff surfaces', async () => {
    render(
      <MemoryRouter initialEntries={['/canvas-sync']}>
        <App />
      </MemoryRouter>,
    )

    expect(await screen.findByText('Conflict Resolution')).toBeInTheDocument()
    expect(await screen.findByText('Snapshot Diff Viewer')).toBeInTheDocument()
    expect(await screen.findByText('Ada Lovelace')).toBeInTheDocument()
    expect(await screen.findByText('course-1:assignment-1:user-1')).toBeInTheDocument()
  })

  it('renders course match workbench route', async () => {
    render(
      <MemoryRouter initialEntries={['/courses/1/matches']}>
        <App />
      </MemoryRouter>,
    )

    expect(await screen.findByText('Match Queue Workbench')).toBeInTheDocument()
    expect(await screen.findByText('Refresh Suggestions')).toBeInTheDocument()
  })

  it('renders collapsible student profile areas with scored assignment rubrics', async () => {
    render(
      <MemoryRouter initialEntries={['/students/42']}>
        <App />
      </MemoryRouter>,
    )

    expect(await screen.findByText('Ada Lovelace')).toBeInTheDocument()
    expect(await screen.findByText('Scored Assignment Rubrics')).toBeInTheDocument()
    expect((await screen.findAllByText('Lab Report')).length).toBeGreaterThan(0)
    expect(await screen.findByText('Research Rubric - 8 / 10')).toBeInTheDocument()
  })

  it('renders the report template builder route', async () => {
    render(
      <MemoryRouter initialEntries={['/reports']}>
        <App />
      </MemoryRouter>,
    )

    expect(await screen.findByText('Report Builder')).toBeInTheDocument()
    expect((await screen.findAllByText('Progress Snapshot')).length).toBeGreaterThan(0)
    expect(await screen.findByText('Student Snapshot')).toBeInTheDocument()
  })

  it('renders the LLM student feedback workflow route', async () => {
    render(
      <MemoryRouter initialEntries={['/llm']}>
        <App />
      </MemoryRouter>,
    )

    expect(await screen.findByText('Student Feedback Workbench')).toBeInTheDocument()
    expect(await screen.findByText('Paper Feedback')).toBeInTheDocument()
    expect(await screen.findByText('Replacement Map')).toBeInTheDocument()
  })
})
